# Fichero .ini que contiene los datos de DDNS 
# y de ubicacion para cada certificado
# 
# la seccion "default" contiene definiciones globales
# que se aplican a todas las secciones, salvo que sean sobreescritas
[default]
# Entrada del fichero de claves para acceso al DNS
ddns_credentials = "ddns-key"
# Entrada del fichero de credenciales ACME
acme_credentials = "default"
# Ubicacion de cada elemento del certificado en el host destino
# Si no están definidos, el certificado no se intenta distribuir
key_path = "/etc/ssl/private/
cert_path = "/etc/ssl/certs/
chain_path = "/usr/share/ca-certificates/

#
# Lista de certificados que se gestionan
#
# Nombre (CN) del certificado
[name.example.com]
# Nombre del host en el que se va a ubicar el certificado. (Requerido)
cert_host = "host.example.com"
# Lista separada por comas de SubjectAlternativeName. (Opcional)
# certbot siempre incluye el CN en esta lista
# NO se permiten wildcards
cert_alt_names = ""
# Entrada activa (1) o inactiva (0). (Requerido)
cert_enabled = 0
#
#
[www.sub.example.com]
cert_host = "www.sub.example.com"
cert_alt_names = ""
cert_enabled = 0

